name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    name: Call Reusable Workflow
    uses: vidyasagarreddyc/artifact-test/.github/workflows/master.yml@main
    with:
      # Pass any required inputs here
    secrets: inherit
