name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type to pass to the reusable workflow'
        required: true
        default: 'manual_trigger'

jobs:
  call-reusable-workflow:
    uses: vidyasagarreddyc/githubactions2/.github/workflows/master.yml@main
    with:
      environment: "dev"
      app_version: "1.0"
