name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type to pass to the reusable workflow'
        required: true
        default: 'manual_trigger'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      event_type: ${{ github.event.inputs.event_type }}
