name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    name: Call Reusable Workflow
    uses: vidyasagarreddyc/githubactions2/.github/workflows/master.yml@main
    with:
      app_version: "1.0"
      environment: "dev"
    
