name: "Reusable Action-json"
on:
  workflow_call:
    inputs:
      json_file:
        description: "Path to the JSON file"
        required: true
        type: string
jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read JSON File
        id: read-json
        run: |
          if [ -f "${{ inputs.json_file }}" ]; then
            echo "JSON content:"
            cat "${{ inputs.json_file }}"
          else
            echo "File not found: ${{ inputs.json_file }}"
            exit 1
          fi
