name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_call:
    inputs:
      MT_NAME:
        description: 'MT Name'
        required: true
        string: true
        
      MT_FOLDER:
        type: string
        description: 'MT Folder location'
        required: true

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "'${{ github.event.inputs.MT_NAME }}'"
      - run: echo "'${{ github.event.inputs.MT_FOLDER }}'"
        
