# .github/workflows/reusable.yml
name: Independent Workflow

on:
  workflow_dispatch: # Allows manual triggering
  workflow_call: # Allows being called by other workflows

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use a secret from this repository
        run: echo "Using secret value: ${{ secrets.TEST_SECRET }}"

