name: "Reusable Action - SECRET"
on:
  workflow_call:
    inputs:
      json_file:
        description: "Path to the JSON file"
        required: true
        type: string
  workflow_dispatch:  # Adds a manual trigger
jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use a secret from this repository
        run: echo "Using secret value {{ secrets.TEST_SECRET }}"
        env:
          SECRET_VALUE: ${{ secrets.TEST_SECRET }}
